import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/ui/base/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Container className="flex flex-col items-center min-h-screen px-4 py-12">
          {children}
        </Container>
      </body>
    </html>
  );
}
